id = "vcard"
name = "vCard"
version = "0.2.0"
schema_version = 1
authors = ["Titouan Real <titouan.real@gmail.com>"]
description = "vCard support."
repository = "https://github.com/TitouanReal/zed-vcard"

[grammars.vcard]
repository = "https://github.com/TitouanReal/tree-sitter-vcard"
rev = "f8016385059fd3b2a5668ef92131293932d8907b"
